global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "flight-service"
    static_configs:
      - targets: ["192.168.1.187:3500"]

  - job_name: "booking-service"
    static_configs:
      - targets: ["192.168.1.187:4000"]
